import torch

v = torch.tensor([1, 2, 3, 4, 5, 6])
print(v)
print(v[1:])

# x = v.view(3, 2)
x = v.reshape(3, 2)
y = v.view(3, 2)
z = v.view(3, -1)
print(v)
print(x)
print(y)
print(z)
# # f = torch.FloatTensor([1, 2, 3, 4, 5, 6])
# # print(f.dtype)
# # print(f.shape)
# # print(f.size())
# v = torch.tensor([1, 1, 1, 1, 1, 1])
# print(v)
# print(x)
# print(y)
